# Teste do módulo árvore usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteArvoreProd
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Arvore
TestArv

[BuildInicio]
/OUT:..\produto\TesteArvoreProd.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
