# Teste de geração números aleatórios

[Diretorios]

Nome        =  TesteAleatorio
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas
tab         =  ..\Tabelas
inc         =  ..\Tabelas

[Modulos]
Princip
Generico
TabSimb
LerParm
CEspDin
Conta
GeraAlt
IntrpCED
IntrpCNT
Testalt

[BuildInicio]
/OUT:..\produto\TesteAleatorio.exe
/INCREMENTAL:NO
/MACHINE:IX86

[Fim]
