#ifndef _TesteTabelaString_str
#define _TesteTabelaString_str

/* !!!!!!!!!! Aquivo gerado! Nao o edite! !!!!!!!!!! */

/****************************************************************************
*
* $AT Tabela de definição de chaves de acesso a strings gerada
*
* Arquivo gerado: .\TesteTabelaString.inc
*
* Projeto: INF 1301/1628 Exemplos
* Gestor:  LES/DI/PUC-Rio
*
* Arquivo de especificação de strings: .\TesteTabelaString.espstr
*
***************************************************************************/

   const int STR10                =   110 ;
   const int STR13                =   113 ;
   const int Str14                =   114 ;
   const int Str15                =   115 ;
   const int STR16                =   116 ;
   const int STR17                =   117 ;
   const int STR20                =   121 ;

#endif

/* Fim tabela de definição gerada */
